[WIP]ソース確認用PR
Ayano-Kaito/exp-date pull request #2
Opened 2021-02-24 15:10 UTC by Ayano-Kaito

2021-02-24 15:13 UTC, Ayano-Kaito commented on src/App.js
> +      .then((res) => setCategories(res.data))
ここでcategoriesに値が入っているか確認したのですが、
いまいちほしい情報が取れて来ている感じではなく、どうしたら良いでしょうか？
ほしい情報：カテゴリー一覧の内容

2021-02-24 23:20 UTC, Ayano-Kaito commented on src/App.js
> +      .then((res) => setCategories(res.data))
取れているっぽいのでOK

2021-03-01 03:30 UTC, kilvistyle requested changes

2021-03-01 03:30 UTC, kilvistyle commented on src/Category/Category.tsx
>  }
`interface`の型名も先頭大文字始まりが良いと思います。
・変数は小文字始まり（LowarCamelCase）
・クラス名、型名、コンポーネント名は先頭大文字始まり（UpperCamelCase）

2021-03-02 00:47 UTC, Ayano-Kaito commented on src/App.js
> +}
category.tsxでmockをimport文には書いているものの表示箇所には書いていなかったので表示されず、console.log(mock)と書くとmockの値を取れるがどう書くのが適切かわからなかった
→千葉さんのソースのように修正して表示されるようになった

2021-03-24 00:17 UTC, Ayano-Kaito commented
一旦editmodalができたのでtaskブランチにマージします。
デザイン修正とバリデーションチェックはaddmodal作成後一緒に修正します。

2021-03-24 00:17 UTC, merged